import type { BootstrapPayload } from "@/types/dashboard";

export const mockBootstrap: BootstrapPayload = {
  appName: "Pulseboard",
  phase: "Foundation shell",
  demoMode: true,
  profile: {
    alias: "Captain Crisp",
    level: 8,
    xp: 1240,
    streakDays: 6,
    companion: "Aurora fox",
  },
  providerStatus: [
    {
      name: "GitLab",
      state: "live",
      host: "gitlab.com",
      authMode: "OAuth PKCE + PAT fallback",
      note: "Primary provider for v1 with local-first sync architecture.",
    },
    {
      name: "YouTrack",
      state: "beta",
      host: "custom",
      authMode: "Planned provider adapter",
      note: "Next in line once GitLab sync contracts are stable.",
    },
    {
      name: "GitHub",
      state: "planned",
      host: "github.com",
      authMode: "Capability review required",
      note: "Issue time models are less native, so adapter design matters.",
    },
    {
      name: "Bitbucket",
      state: "planned",
      host: "bitbucket.org",
      authMode: "Capability review required",
      note: "Scheduled after provider abstraction hardens.",
    },
  ],
  schedule: {
    hoursPerDay: 8,
    workdays: "Mon - Fri",
    timezone: "America/Argentina/Buenos_Aires",
    syncWindow: "Current + previous month",
    mode: "Read-only audit mode",
  },
  today: {
    shortLabel: "Today",
    dateLabel: "Friday",
    loggedHours: 6.8,
    targetHours: 8,
    focusHours: 5.7,
    overflowHours: 0,
    status: "on_track",
    topIssues: [
      { key: "GL-482", title: "OAuth callback spike", hours: 3.1, tone: "emerald" },
      { key: "GL-499", title: "Tray HUD styling", hours: 2.2, tone: "cyan" },
      { key: "GL-512", title: "SQLite schema pass", hours: 1.5, tone: "amber" },
    ],
  },
  week: [
    {
      shortLabel: "Mon",
      dateLabel: "Mon 03",
      loggedHours: 8,
      targetHours: 8,
      focusHours: 6.4,
      overflowHours: 0,
      status: "met_target",
      topIssues: [
        { key: "GL-470", title: "Provider contracts", hours: 3.4, tone: "violet" },
      ],
    },
    {
      shortLabel: "Tue",
      dateLabel: "Tue 04",
      loggedHours: 7.3,
      targetHours: 8,
      focusHours: 6.1,
      overflowHours: 0,
      status: "under_target",
      topIssues: [
        { key: "GL-476", title: "Schedule bucket rules", hours: 2.9, tone: "amber" },
      ],
    },
    {
      shortLabel: "Wed",
      dateLabel: "Wed 05",
      loggedHours: 8.6,
      targetHours: 8,
      focusHours: 7.2,
      overflowHours: 0.6,
      status: "over_target",
      topIssues: [
        { key: "GL-481", title: "Audit view sorting", hours: 4.2, tone: "rose" },
      ],
    },
    {
      shortLabel: "Thu",
      dateLabel: "Thu 06",
      loggedHours: 8,
      targetHours: 8,
      focusHours: 6.8,
      overflowHours: 0,
      status: "met_target",
      topIssues: [
        { key: "GL-488", title: "Glass UI system", hours: 3.7, tone: "cyan" },
      ],
    },
    {
      shortLabel: "Fri",
      dateLabel: "Fri 07",
      loggedHours: 6.8,
      targetHours: 8,
      focusHours: 5.7,
      overflowHours: 0,
      status: "on_track",
      topIssues: [
        { key: "GL-482", title: "OAuth callback spike", hours: 3.1, tone: "emerald" },
      ],
    },
  ],
  month: {
    loggedHours: 119.4,
    targetHours: 136,
    consistencyScore: 88,
    cleanDays: 11,
    overflowDays: 2,
  },
  auditFlags: [
    {
      title: "Wednesday exceeded target by 0.6h",
      severity: "medium",
      detail: "Review GL-481 and GL-488 for duplicate or late-posted entries.",
    },
    {
      title: "Tuesday closed under target",
      severity: "high",
      detail: "0.7h missing after end of workday. Audit issue notes before weekly close.",
    },
    {
      title: "Current sync is using demo payload",
      severity: "low",
      detail: "GitLab auth, secure storage, and live sync are next implementation slices.",
    },
  ],
  quests: [
    { title: "Land five clean workdays", progress: 4, total: 5, reward: "+120 XP" },
    { title: "Keep overflow below 1h", progress: 1, total: 1, reward: "Pet aura" },
    { title: "Ship GitLab auth spike", progress: 2, total: 3, reward: "OAuth badge" },
  ],
};
