import type { BootstrapPayload } from "@/shared/types/dashboard";

/**
 * Rich mock payload injected during the onboarding tour so users can see
 * what a fully populated Timely looks like before connecting GitLab.
 */
export const tourPayload: BootstrapPayload = {
  appName: "Timely",
  phase: "Foundation shell",
  demoMode: true,
  lastSyncedAt: "2026-03-05T14:13:00Z",
  profile: {
    alias: "Alex Rivera",
    level: 7,
    xp: 1050,
    streakDays: 12,
    companion: "Aurora fox",
  },
  streak: {
    currentDays: 4,
    window: [
      { date: "2026-02-27", state: "counted", isToday: false },
      { date: "2026-02-28", state: "skipped", isToday: false },
      { date: "2026-03-01", state: "skipped", isToday: false },
      { date: "2026-03-02", state: "counted", isToday: false },
      { date: "2026-03-03", state: "counted", isToday: false },
      { date: "2026-03-04", state: "counted", isToday: false },
      { date: "2026-03-05", state: "counted", isToday: true },
    ],
  },
  providerStatus: [
    {
      name: "GitLab",
      state: "live",
      host: "gitlab.com",
      authMode: "PAT",
      note: "Connected · last synced 2 min ago",
    },
  ],
  schedule: {
    hoursPerDay: 8,
    shiftStart: "09:00",
    shiftEnd: "18:00",
    lunchMinutes: 60,
    workdays: "Mon - Tue - Wed - Thu - Fri",
    timezone: "America/Santiago",
  },
  today: {
    date: "2026-03-05",
    shortLabel: "Wed",
    dateLabel: "Wed 05",
    isToday: true,
    holidayName: undefined,
    loggedHours: 6.25,
    targetHours: 8,
    focusHours: 4.5,
    overflowHours: 0,
    status: "on_track",
    topIssues: [
      {
        key: "PULSE-42",
        title: "Redesign dashboard layout",
        hours: 2.5,
        tone: "violet",
      },
      {
        key: "PULSE-38",
        title: "Fix timezone offset bug",
        hours: 1.75,
        tone: "emerald",
      },
      {
        key: "PULSE-51",
        title: "Add dark mode support",
        hours: 1.25,
        tone: "cyan",
      },
      {
        key: "PULSE-47",
        title: "Write API integration tests",
        hours: 0.75,
        tone: "amber",
      },
    ],
  },
  week: [
    {
      date: "2026-03-01",
      shortLabel: "Mon",
      dateLabel: "Mon 01",
      isToday: false,
      holidayName: undefined,
      loggedHours: 8.5,
      targetHours: 8,
      focusHours: 6,
      overflowHours: 0.5,
      status: "over_target",
      topIssues: [],
    },
    {
      date: "2026-03-02",
      shortLabel: "Tue",
      dateLabel: "Tue 02",
      isToday: false,
      holidayName: undefined,
      loggedHours: 7.75,
      targetHours: 8,
      focusHours: 5.25,
      overflowHours: 0,
      status: "met_target",
      topIssues: [],
    },
    {
      date: "2026-03-03",
      shortLabel: "Wed",
      dateLabel: "Wed 03",
      isToday: true,
      holidayName: undefined,
      loggedHours: 6.25,
      targetHours: 8,
      focusHours: 4.5,
      overflowHours: 0,
      status: "on_track",
      topIssues: [],
    },
    {
      date: "2026-03-04",
      shortLabel: "Thu",
      dateLabel: "Thu 04",
      isToday: false,
      holidayName: "Founders Day",
      loggedHours: 0,
      targetHours: 8,
      focusHours: 0,
      overflowHours: 0,
      status: "empty",
      topIssues: [],
    },
    {
      date: "2026-03-05",
      shortLabel: "Fri",
      dateLabel: "Fri 05",
      isToday: false,
      holidayName: undefined,
      loggedHours: 0,
      targetHours: 8,
      focusHours: 0,
      overflowHours: 0,
      status: "empty",
      topIssues: [],
    },
  ],
  month: {
    loggedHours: 38.7,
    targetHours: 160,
    consistencyScore: 85,
    cleanDays: 8,
    overflowDays: 2,
  },
  auditFlags: [
    {
      title: "Overtime on Monday",
      severity: "low",
      detail: "Logged 8.5h against an 8h target. 0.5h overflow was recorded.",
    },
    {
      title: "No entries for Thursday",
      severity: "medium",
      detail:
        "Thursday has 0h logged. If this is a workday, you may want to check for missing time entries.",
    },
    {
      title: "Consistency below 90%",
      severity: "high",
      detail:
        "Your monthly consistency score is 85%. Try to log time consistently each workday to improve this.",
    },
  ],
  quests: [
    {
      title: "Log 5 consecutive days",
      progress: 3,
      total: 5,
      reward: "+150 XP",
    },
    {
      title: "Hit daily target 10 times",
      progress: 7,
      total: 10,
      reward: "+300 XP",
    },
    {
      title: "Track 3 different projects",
      progress: 2,
      total: 3,
      reward: "+100 XP",
    },
  ],
};
